import type { WorkflowSource } from "@foundation/types";

export const workflowSources: WorkflowSource[] = [
  {
    id: "WF1",
    title: "AI Enablement Workshop & Roadmap",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 95, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 3, daysMax: 4, weeks: "3–4 weken", daysLabel: "26–28 uur" },
    cost: { min: 4500, max: 4500 },
    investmentLabel: "€4.500",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Human-First, AI-Empowered — van grunt work naar strategische impact, voor elk team binnen Adsomnia.",
    why: "AI is niet hier om te leiden — het is hier om te ondersteunen. De mensen van Adsomnia zijn de motor: hun creativiteit, strategisch denken en ondernemersdrive zijn wat het verschil maakt. Te veel energie gaat nu verloren aan handmatig werk, data ophalen en repetitieve taken. Deze workshop geeft elk team de kennis, de tools en een concreet pad om AI in te zetten als co-piloot — zodat de tijd en mentale ruimte vrijkomt voor wat echt impact maakt.",
    benefits: [
      "Elk team snapt wat AI voor hun werk betekent — niet abstract, maar concreet en toepasbaar",
      "Gedeelde AI-roadmap: wat nu, wat daarna, wat samen — gedragen door het hele team",
      "Fundament voor een duurzame manier van werken met AI binnen Adsomnia",
    ],
    timeSaved: "Van grunt work naar strategische focus — structureel meer tijd voor wat er echt toe doet",
    deliverables: [
      "Milestone #1 – Inspire, Awareness & Enable (29 juli, 14:00–17:00): AI-visie kick-off, capabilities showcase, live Claude demo's, No-Regret Use Case Framework, breakout sessies per afdeling, presentatie en selectie per team",
      "Milestone #2 – Analyse, Review & Validatie: review van alle use cases en Claude-prototypes per afdeling, technische en business-validatie",
      "Milestone #3 – Deep-dive & Prioritering: presentatie use cases, feedback, prioriteren van quick wins en strategische initiatieven, gezamenlijke selectie van kansrijke projecten",
      "Milestone #4 – Strategische Roadmap & Business Cases: NOW / NEXT / NEAR AI-roadmap uitgewerkt, business cases voor de geselecteerde initiatieven",
    ],
  },
  {
    id: "WF2",
    title: "Project & Product Enablement",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 2.5, confidencePct: 85, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 3, daysMax: 5, weeks: "4–6 weken", daysLabel: "20–30 uur" },
    cost: { min: 3000, max: 3000 },
    investmentLabel: "€3.000",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Fundament, werkwijze en tooling ingericht — zodat teams daadwerkelijk kunnen samenwerken en leveren.",
    why: "AI-initiatieven slagen of falen op uitvoering. Zonder heldere projectstructuur, een afgestemde manier van werken en de juiste tooling-setup stranden de mooiste plannen in de dagelijkse waan van de dag. Dit project legt het fundament waarop alles daarna gebouwd wordt.",
    benefits: [
      "Jira (of vergelijkbare tooling) ingericht passend bij hoe Adsomnia werkt",
      "Eén gedeeld stramien: hoe pakken we projecten aan, wie beslist wat",
      "Duidelijke werkwijze voor samenwerking tussen teams",
      "Projectflows die schaalbaar zijn naarmate er meer AI-projecten bijkomen",
      "Minder ad-hoc afstemming, meer gestructureerd leveren",
    ],
    timeSaved: "Uren per week minder miscommunicatie en onduidelijkheid",
    deliverables: [
      "Analyse van hoe Adsomnia nu werkt en waar de frictie zit",
      "Jira (of bestaande tooling) ingericht met projectflows, statussen en ritme",
      "Werkwijze-document: rollen, beslisregels, communicatielijnen, sprintritme",
      "Onboarding voor het team — iedereen weet hoe het werkt",
      "Stramien voor het oppakken van nieuwe projecten (inclusief AI-initiatieven uit de workshop)",
    ],
  },
  {
    id: "WF3",
    title: "Samenwerking & Retainer",
    bucket: "Incremental",
    rice: { reach: 10, impact: 2, confidencePct: 90, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 0, daysMax: 0, weeks: "Doorlopend", daysLabel: "Doorlopend" },
    cost: { min: 0, max: 0 },
    investmentLabel: "Nader te bepalen",
    excludeFromTotals: true,
    excludeFromPrio: true,
    hideTimeline: true,
    summary: "Structurele samenwerking: AI-implementatie, technische begeleiding en projectmanagement als vliegende keep.",
    why: "Na de workshop liggen er concrete initiatieven op tafel. Die moeten ook echt landen. En tegelijk groeit de behoefte aan strakker projectmanagement over de hele organisatie. Met een dedicated samenwerking is blablabuild beschikbaar als verlengstuk van het team — niet als extern bureau dat je telkens opnieuw moet briefen.",
    benefits: [
      "Directe ondersteuning bij het implementeren van AI-projecten uit de roadmap",
      "Technical guidance: architectuurkeuzes, toolselectie, prompt engineering",
      "Productmanagement / projectmanagement als vliegende keep over de organisatie",
      "Continuïteit: blablabuild kent de context, geen opstarttijd bij elk vraagstuk",
      "Flexibel: retainer op uurbasis of dedicated x uur per week",
    ],
    timeSaved: "Geen opstart- en briefingkosten bij elk nieuw vraagstuk",
    deliverables: [
      "Wekelijkse of tweewekelijkse afstemming",
      "Begeleiding bij implementatie van AI-initiatieven uit de workshop",
      "Technical support en sparring bij architectuur- en toolkeuzes",
      "PM/PO-rol als vliegende keep: prioriteitenlijst, ritme, voortgang bewaken",
      "Maandelijks overzicht van voortgang en aanbevelingen",
    ],
  },
];
