import type { WorkflowSource } from "@foundation/types";

export const workflowSources: WorkflowSource[] = [
  {
    id: "WF1",
    title: "AI Enablement Workshop & Roadmap",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 95, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 3, daysMax: 4, weeks: "3–4 weeks", daysLabel: "26–28 hrs" },
    cost: { min: 4500, max: 4500 },
    investmentLabel: "€4.5K",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Human-First, AI-Empowered — from grunt work to strategic impact, for every team at Adsomnia.",
    why: "AI is not here to lead — it is here to support. The people at Adsomnia are the engine: their creativity, strategic thinking, and entrepreneurial drive are what make the difference. Too much energy is currently lost to manual work, data retrieval, and repetitive tasks. This workshop gives every team the knowledge, the tools, and a concrete path to deploy AI as a co-pilot — freeing up time and mental space for what truly matters.",
    benefits: [],
    timeSaved: "From grunt work to strategic focus — structurally more time for what truly matters",
    deliverables: [
      "Milestone #1 – Inspire, Awareness & Enable (29 July, 14:00–17:00): AI vision kick-off, capabilities showcase, live Claude demos, No-Regret Use Case Framework, breakout sessions per department, presentation and selection per team",
      "Milestone #2 – Analysis, Review & Validation: review of all use cases and Claude prototypes per department, technical and business validation",
      "Milestone #3 – Deep-dive & Prioritisation: use case presentations, feedback, prioritising quick wins and strategic initiatives, joint selection of promising projects",
      "Milestone #4 – Strategic Roadmap & Business Cases: NOW / NEXT / NEAR AI roadmap developed, business cases for the selected initiatives",
    ],
  },
  {
    id: "WF2",
    title: "Project & Production Enablement",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 2.5, confidencePct: 85, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 3, daysMax: 5, weeks: "4–6 weeks", daysLabel: "20–30 hrs" },
    cost: { min: 0, max: 0 },
    investmentLabel: "€3.5K–€6K",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    hideDeliverables: true,
    summary: "A centralised overview of all active projects, the right toolstack, and the foundation for a PM / PO role.",
    expectedValue: "Before we design the setup, we run a pre-exploration. We look at the team, how they currently work, what projects exist, and who picks them up — internal, external, or within the broader organisation. We also map how this evolves as Adsomnia grows: internal team, dedicated team, or staying external. Only then do we determine the approach and toolstack that genuinely fits.",
    why: "Adsomnia is growing — and so is the complexity of projects, people, and tools. Right now there is no central overview of what is running, who owns what, and how that scales. Without structure now, coordination becomes a problem later.",
    benefits: [],
    timeSaved: "From ad-hoc coordination to structured oversight and ownership",
    deliverables: [
      "Pre-exploration: analysis of the team, current way of working, project landscape, and future scenarios (internal, external, or within the broader organisation)",
      "Toolstack recommendation based on the exploration: Project Management (Jira), Storage (Google Drive), Resource Planning, and Central Production Dashboard (Jira or bespoke)",
      "Configuration of the chosen toolstack with workflows, statuses, and a rhythm that fits Adsomnia",
      "Central production dashboard: overview of all active projects, ownership, and status",
      "Fully documented foundation ready for a PM / PO — whether that person is already in place or still being sourced",
    ],
  },
  {
    id: "WF3",
    title: "Always-On Retainer",
    bucket: "Incremental",
    rice: { reach: 10, impact: 2, confidencePct: 90, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 0, daysMax: 0, weeks: "Ongoing", daysLabel: "Ongoing" },
    cost: { min: 0, max: 0 },
    investmentLabel: "X hrs/week",
    excludeFromTotals: true,
    excludeFromPrio: true,
    hideTimeline: true,
    domainLabels: ["Innovation", "Production", "Business"],
    summary: "A fixed block of hours per week — flexibly deployable across Innovation, Production, and Business. Your safety net, always in context.",
    why: "Growth brings complexity. New AI initiatives that need to land. Production issues you cannot afford to leave unresolved. Strategic choices you do not want to face alone. We agree on a fixed number of hours per week — likely structured around fixed days. Those hours are yours to direct: this week mostly production, next week strategy, the week after a deep-dive on a new AI initiative. No briefing cost, no ramp-up, always in context.",
    benefits: [
      "Production: your safety net and direct support for project leads and the PM-to-be — available for blockers, bugs, and escalations before they become problems",
      "Innovation: we help think through and execute the AI use cases and initiatives coming from the workshop roadmap — co-building, supporting new ideas as they emerge, and making sure innovation actually moves forward rather than stalling after the workshop",
      "Business: we are your strategic partner — sparring on choices, roadmap, and priorities",
      "You decide where the hours go — split across the three areas based on what is most pressing that week",
    ],
    timeSaved: "The certainty that someone is always there to think along and step in",
    deliverables: [
      "Weekly or bi-weekly alignment — always on top of what is happening",
      "Production support: direct availability for blockers, bugs, and escalations",
      "Innovation: thinking through use cases from the AI roadmap, co-building and realising AI initiatives, supporting new ideas as they emerge",
      "Business sparring: strategy, roadmap, priorities, and decision support",
      "Monthly overview: where did the hours go, what was delivered, what is coming next",
    ],
  },
];
