import type { WorkflowSource } from "@foundation/types";

export const workflowSourcesNl: WorkflowSource[] = [
  {
    id: "WF1",
    title: "AI Enablement Workshop & Roadmap",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 95, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 3, daysMax: 4, weeks: "3–4 weken", daysLabel: "26–28 uur" },
    cost: { min: 4500, max: 4500 },
    investmentLabel: "€4.5K",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Human-First, AI-Empowered — van grunt work naar strategische impact, voor elk team binnen Adsomnia.",
    why: "AI is niet hier om te leiden — het is hier om te ondersteunen. De mensen van Adsomnia zijn de motor: hun creativiteit, strategisch denken en ondernemersdrive zijn wat het verschil maakt. Te veel energie gaat nu verloren aan handmatig werk, data ophalen en repetitieve taken. Deze workshop geeft elk team de kennis, de tools en een concreet pad om AI in te zetten als co-piloot — zodat de tijd en mentale ruimte vrijkomt voor wat echt impact maakt.",
    benefits: [],
    timeSaved: "Van grunt work naar strategische focus — structureel meer tijd voor wat er echt toe doet",
    deliverables: [
      "Milestone #1 — Workshop: Inspire, Awareness & Enable (woensdag 29 juli, 14:00–17:00): intro blablabuild en voorbeelden uit eigen werk · de Adsomnia AI-visie vertaald naar concrete doelstellingen per afdeling · deep-dive in AI agents (wat is er nu al mogelijk, wanneer heb je een agent nodig?) + Agentic Enterprise demo (Talk-To-Data) · live Claude omgeving demo inclusief één volledig gebouwde agent die van de achterkant wordt getoond · introductie van het No-Regret Use Case Framework · breakout sessies per afdeling: elk team werkt minimaal 3 potentiële use cases uit · gezamenlijke presentatie en selectie van een Claude Code Case per team (volledig autonoom te maken in Claude) · huiswerk: Use Case Framework volledig gemaakt binnen 7 dagen, Claude prototype uitgewerkt binnen 14 dagen",
      "Milestone #2 — Analyse, Review & Validatie: blablabuild ontvangt alle uitgewerkte use cases en Claude-prototypes · beoordeling technische haalbaarheid binnen de bestaande tech-suite · voorbereiding van gerichte vragen en optimalisaties voor de volgende sessie",
      "Milestone #3 — Workshop: Deep-dive & Prioritering (midden augustus): teams presenteren hun Claude-prototype — kennisdeling en inspiratie · Q&A over alle ingediende use cases · collectieve visuele prioritering: direct inzichtelijk welke cases quick wins zijn en welke meer strategisch gewicht hebben",
      "Milestone #4 — Strategische Roadmap & Business Cases: blablabuild vertaalt de geselecteerde top-cases naar concrete projectplannen · resulteert in een NOW / NEXT / NEAR AI-roadmap — exact welke 2–3 cases als eerste gebouwd worden, welke daarna volgen en welke op de lange termijn staan",
    ],
  },
  {
    id: "WF2",
    title: "Project & Production Enablement",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 2.5, confidencePct: 85, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 3, daysMax: 5, weeks: "4–6 weken", daysLabel: "20–30 uur" },
    cost: { min: 0, max: 0 },
    investmentLabel: "€3.5K–€6K",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    hideDeliverables: true,
    summary: "Gecentraliseerd overzicht van alle lopende projecten, de juiste toolstack en het fundament voor een PM / PO-rol.",
    expectedValue: "Voordat we de inrichting bepalen, doen we een voorverkenning. We kijken naar het team, hoe ze nu werken, welke projecten er zijn en wie ze oppakt — intern, extern of binnen de bredere organisatie. We brengen ook in kaart hoe dit evolueert als Adsomnia verder groeit: intern team, dedicated team, of blijft het extern. Pas dan bepalen we de aanpak en toolstack die écht past.",
    why: "Adsomnia groeit — en daarmee de complexiteit van projecten, mensen en tools. Op dit moment ontbreekt een centraal overzicht van wat er loopt, wie wat doet en hoe dat schaalt. Zonder structuur nu, wordt coördinatie later een probleem.",
    benefits: [],
    timeSaved: "Van ad-hoc coördinatie naar gestructureerd overzicht en eigenaarschap",
    deliverables: [
      "Voorverkenning: analyse van het team, huidige werkwijze, projectlandschap en toekomstscenario's (intern, extern, binnen de bredere organisatie)",
      "Advies toolstack op basis van de verkenning: Project Management (Jira), Storage (Google Drive), Resource Planning, Planning en Central Production Dashboard (Jira of bespoke)",
      "Inrichting van de gekozen toolstack met workflows, statussen en ritme passend bij Adsomnia",
      "Centraal productie-dashboard: overzicht van alle lopende projecten, eigenaarschap en status",
      "Volledig gedocumenteerd fundament klaar voor een PM / PO — ongeacht of die er al is of nog wordt gezocht",
    ],
  },
  {
    id: "WF3",
    title: "Always-On Retainer",
    bucket: "Incremental",
    rice: { reach: 10, impact: 2, confidencePct: 90, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 0, daysMax: 0, weeks: "Doorlopend", daysLabel: "Doorlopend" },
    cost: { min: 0, max: 0 },
    investmentLabel: "X uur/week",
    excludeFromTotals: true,
    excludeFromPrio: true,
    hideTimeline: true,
    domainLabels: ["Innovatie", "Productie", "Business"],
    summary: "Een vast blok uren per week — flexibel in te zetten over Innovatie, Productie en Business. Jouw vangnet, altijd in context.",
    why: "Groei brengt complexiteit mee. Nieuwe AI-initiatieven die moeten landen. Productieproblemen die je niet kunt laten liggen. Strategische keuzes waarbij je niet alleen wil staan. We spreken een vast aantal uur per week af — waarschijnlijk op vaste dagen. Die uren zijn voor jou: deze week vooral productie, volgende week strategie, de week daarna een deep-dive op een nieuw AI-initiatief. Geen briefingkosten, geen opstarttijd, altijd in context.",
    benefits: [
      "Productie: jouw vangnet én directe support voor projectleads en de PM-to-be — beschikbaar bij blokkades, bugs en escalaties voordat ze problemen worden",
      "Innovatie: we helpen bij het uitdenken en realiseren van de AI use cases en initiatieven uit de workshop-roadmap — meedenken, mede-bouwen en zorgen dat de innovatie daadwerkelijk vooruit blijft gaan in plaats van stilstand na de workshop",
      "Business: wij zijn je strategisch partner — sparring bij keuzes, roadmap en prioriteiten",
      "Jij bepaalt waar de uren naartoe gaan — verdeeld over de drie gebieden op basis van wat er die week het hardst nodig is",
    ],
    timeSaved: "Zekerheid dat er altijd iemand is die meedenkt en bijspringt",
    deliverables: [
      "Wekelijkse of tweewekelijkse afstemming — altijd op de hoogte van wat er speelt",
      "Productie support: directe beschikbaarheid bij blokkades, bugs en escalaties",
      "Innovatie: uitdenken van use cases uit de AI-roadmap, mede-bouwen en realiseren van AI-initiatieven, ondersteunen van nieuwe ideeën die ontstaan",
      "Business sparring: strategie, roadmap, prioriteiten en beslissingssupport",
      "Maandelijks overzicht: waar zijn de uren gevallen, wat is opgeleverd, wat staat er voor volgende maand",
    ],
  },
];
