import type { WorkflowSource } from "@foundation/types";

export const workflowSources: WorkflowSource[] = [
  {
    id: "WF1",
    title: "AI Enablement Workshop & Roadmap",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 95, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 3, daysMax: 4, weeks: "3–4 weeks", daysLabel: "26–28 hrs" },
    cost: { min: 4500, max: 4500 },
    investmentLabel: "€4.500",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Human-First, AI-Empowered — from grunt work to strategic impact, for every team at Adsomnia.",
    why: "AI is not here to lead — it is here to support. The people at Adsomnia are the engine: their creativity, strategic thinking, and entrepreneurial drive are what make the difference. Too much energy is currently lost to manual work, data retrieval, and repetitive tasks. This workshop gives every team the knowledge, the tools, and a concrete path to deploy AI as a co-pilot — freeing up time and mental space for what truly matters.",
    benefits: [
      "Every team understands what AI means for their work — not abstract, but concrete and actionable",
      "Shared AI roadmap: what now, what next, what together — owned by the whole team",
      "Foundation for a sustainable way of working with AI across Adsomnia",
    ],
    timeSaved: "From grunt work to strategic focus — structurally more time for what truly matters",
    deliverables: [
      "Milestone #1 – Inspire, Awareness & Enable (29 July, 14:00–17:00): AI vision kick-off, capabilities showcase, live Claude demos, No-Regret Use Case Framework, breakout sessions per department, presentation and selection per team",
      "Milestone #2 – Analysis, Review & Validation: review of all use cases and Claude prototypes per department, technical and business validation",
      "Milestone #3 – Deep-dive & Prioritisation: use case presentations, feedback, prioritising quick wins and strategic initiatives, joint selection of promising projects",
      "Milestone #4 – Strategic Roadmap & Business Cases: NOW / NEXT / NEAR AI roadmap developed, business cases for the selected initiatives",
    ],
  },
  {
    id: "WF2",
    title: "Project & Production Enablement",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 2.5, confidencePct: 85, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 3, daysMax: 5, weeks: "4–6 weeks", daysLabel: "20–30 hrs" },
    cost: { min: 0, max: 0 },
    investmentLabel: "€3.500–€6.000",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "A centralised overview of all active projects, a working toolstack, and the foundation for a Head of Production role.",
    why: "Adsomnia is growing — and so is the complexity of projects, people, and tools. Right now there is no central overview of what is running, who owns what, and how that scales as the organisation grows. This project starts with a pre-exploration: we look at the team, how they currently work, what projects exist, who picks them up (internal, external, or within the broader organisation), and how this evolves over time. Only then do we decide on the best setup — so the structure genuinely fits Adsomnia, now and later.",
    benefits: [
      "One central overview of all active projects — always up to date, visible to everyone",
      "The foundation is ready for a Project / Product Manager — internal or new hire — to work from day one",
      "Toolstack decided and configured: Jira, Google Drive, and whatever else is needed",
      "A way of working that scales — whether Adsomnia grows internally, works externally, or gets a dedicated team",
      "Foundation for future AI initiatives coming out of the workshop",
    ],
    timeSaved: "From ad-hoc coordination to structured oversight and ownership",
    deliverables: [
      "Pre-exploration: analysis of the team, current way of working, project landscape, and future scenarios (internal, external, within Bending the Rules)",
      "Toolstack recommendation based on the exploration: Project Management (Jira), Storage (Google Drive), Resource Planning, and Central Production Dashboard (Jira or bespoke)",
      "Configuration of the chosen toolstack with workflows, statuses, and a rhythm that fits Adsomnia",
      "Central production dashboard: overview of all active projects, ownership, and status",
      "Fully documented foundation ready for a Project / Product Manager — whether that person is already in place or still being sourced",
    ],
  },
  {
    id: "WF3",
    title: "Always-On Retainer",
    bucket: "Incremental",
    rice: { reach: 10, impact: 2, confidencePct: 90, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 0, daysMax: 0, weeks: "Ongoing", daysLabel: "Ongoing" },
    cost: { min: 0, max: 0 },
    investmentLabel: "X hrs/week · to be confirmed",
    excludeFromTotals: true,
    excludeFromPrio: true,
    hideTimeline: true,
    domainLabels: ["Innovation", "Production", "Business"],
    summary: "Call us in whenever you need. We are your safety net on production, the driver of innovation, and your strategic sparring partner in business.",
    why: "Growth brings complexity. New AI initiatives that need to land. Production issues you cannot afford to leave unresolved. Strategic choices you do not want to face alone. With the Always-On Retainer, blablabuild is always within reach — no ramp-up time, no briefing cost. We agree on a fixed number of hours per week that you can distribute flexibly across the three areas where the need is greatest.",
    benefits: [
      "Production: we are your safety net — issues are picked up immediately, no waiting",
      "Innovation: we keep the rhythm — AI initiatives from the workshop stay alive and actually land",
      "Business: we are your strategic partner — sparring on choices, roadmap, and priorities",
      "Always in context, no ramp-up cost on every new challenge",
      "You decide where the hours go based on what is happening right now",
    ],
    timeSaved: "The certainty that someone is always there to think along and step in",
    deliverables: [
      "Weekly or bi-weekly alignment — always on top of what is happening",
      "Production support: direct availability for blockers, bugs, or urgent matters",
      "Innovation guidance: implementation of AI initiatives, technical decisions, prompt engineering",
      "Business sparring: strategy, roadmap, priorities, and decision support",
      "Monthly overview: where did the hours go, what was delivered, what is coming next",
    ],
  },
];
