import type { WorkflowSource } from "@foundation/types";

export const workflowSources: WorkflowSource[] = [
  {
    id: "WF1",
    title: "AI Enablement Workshop & Roadmap",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 95, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 3, daysMax: 4, weeks: "3–4 weken", daysLabel: "26–28 uur" },
    cost: { min: 4500, max: 4500 },
    investmentLabel: "€4.500",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Human-First, AI-Empowered — van grunt work naar strategische impact, voor elk team binnen Adsomnia.",
    why: "AI is niet hier om te leiden — het is hier om te ondersteunen. De mensen van Adsomnia zijn de motor: hun creativiteit, strategisch denken en ondernemersdrive zijn wat het verschil maakt. Te veel energie gaat nu verloren aan handmatig werk, data ophalen en repetitieve taken. Deze workshop geeft elk team de kennis, de tools en een concreet pad om AI in te zetten als co-piloot — zodat de tijd en mentale ruimte vrijkomt voor wat echt impact maakt.",
    benefits: [
      "Elk team snapt wat AI voor hun werk betekent — niet abstract, maar concreet en toepasbaar",
      "Gedeelde AI-roadmap: wat nu, wat daarna, wat samen — gedragen door het hele team",
      "Fundament voor een duurzame manier van werken met AI binnen Adsomnia",
    ],
    timeSaved: "Van grunt work naar strategische focus — structureel meer tijd voor wat er echt toe doet",
    deliverables: [
      "Milestone #1 – Inspire, Awareness & Enable (29 juli, 14:00–17:00): AI-visie kick-off, capabilities showcase, live Claude demo's, No-Regret Use Case Framework, breakout sessies per afdeling, presentatie en selectie per team",
      "Milestone #2 – Analyse, Review & Validatie: review van alle use cases en Claude-prototypes per afdeling, technische en business-validatie",
      "Milestone #3 – Deep-dive & Prioritering: presentatie use cases, feedback, prioriteren van quick wins en strategische initiatieven, gezamenlijke selectie van kansrijke projecten",
      "Milestone #4 – Strategische Roadmap & Business Cases: NOW / NEXT / NEAR AI-roadmap uitgewerkt, business cases voor de geselecteerde initiatieven",
    ],
  },
  {
    id: "WF2",
    title: "Project & Production Enablement",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 2.5, confidencePct: 85, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 3, daysMax: 5, weeks: "4–6 weken", daysLabel: "20–30 uur" },
    cost: { min: 0, max: 0 },
    investmentLabel: "€3.500–€6.000",
    hideTimeline: true,
    excludeFromPrio: true,
    excludeFromTotals: true,
    summary: "Gecentraliseerd overzicht van alle lopende projecten, een werkende toolstack en iemand intern die als Head of Production kan doorgroeien.",
    why: "Adsomnia groeit — en daarmee de complexiteit van projecten, mensen en tools. Op dit moment ontbreekt een centraal overzicht van wat er loopt, wie wat doet en hoe dat schaalt als de organisatie verder groeit. Dit project begint met een voorverkenning: we kijken naar het team, hoe ze nu werken, welke projecten er zijn, wie ze oppakt (intern, extern of binnen de bredere organisatie) en hoe dit evolueert. Pas dan bepalen we de beste inrichting — zodat de structuur écht past bij Adsomnia, nu en later.",
    benefits: [
      "Eén centraal overzicht van alle lopende projecten — altijd actueel, voor iedereen zichtbaar",
      "Het fundament staat klaar voor een Project / Product Manager — intern of te werven — om direct vanuit te werken",
      "Tool stack bepaald en ingericht: Jira, Google Drive en wat er verder nodig is",
      "Werkwijze die schaalt — of Adsomnia nu extern werkt, intern groeit of een dedicated team krijgt",
      "Fundament voor toekomstige AI-initiatieven uit de workshop",
    ],
    timeSaved: "Van ad-hoc coördinatie naar gestructureerd overzicht en eigenaarschap",
    deliverables: [
      "Voorverkenning: analyse van het team, huidige werkwijze, projectlandschap en toekomstscenario's (intern, extern, within Bending the Rules)",
      "Advies toolstack op basis van de verkenning: Project Management (Jira), Storage (Google Drive), Resource Planning, Planning en Central Production Dashboard (Jira of bespoke)",
      "Inrichting van de gekozen toolstack met workflows, statussen en ritme passend bij Adsomnia",
      "Centraal productie-dashboard: overzicht van alle lopende projecten, eigenaarschap en status",
      "Volledig gedocumenteerd fundament klaar voor een Project / Product Manager — ongeacht of die er al is of nog wordt gezocht",
    ],
  },
  {
    id: "WF3",
    title: "Always-On Retainer",
    bucket: "Incremental",
    rice: { reach: 10, impact: 2, confidencePct: 90, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 0, daysMax: 0, weeks: "Doorlopend", daysLabel: "Doorlopend" },
    cost: { min: 0, max: 0 },
    investmentLabel: "X uur/week · nader te bepalen",
    excludeFromTotals: true,
    excludeFromPrio: true,
    hideTimeline: true,
    domainLabels: ["Innovatie", "Productie", "Business"],
    summary: "Schakel ons in wanneer je wil. Wij zijn jouw vangnet op productie, de aanjager van innovatie en jouw strategisch sparringpartner in business.",
    why: "Groei brengt complexiteit mee. Nieuwe AI-initiatieven die moeten landen. Productieproblemen die je niet kunt laten liggen. Strategische keuzes waarbij je niet alleen wil staan. Met de Always-On Retainer is blablabuild altijd binnen handbereik — geen opstarttijd, geen briefingkosten. We spreken een vast aantal uur per week af dat je flexibel kunt verdelen over de drie gebieden waar de behoefte het grootst is.",
    benefits: [
      "Productie: wij zijn je vangnet — problemen worden direct opgepakt, geen wachttijd",
      "Innovatie: wij zorgen voor ritme — AI-initiatieven uit de workshop blijven leven en landen",
      "Business: wij zijn je strategisch partner — sparring bij keuzes, roadmap en prioriteiten",
      "Altijd in context, geen opstarttijd bij elk nieuw vraagstuk",
      "Jij bepaalt waar de uren naartoe gaan op basis van wat er op dat moment speelt",
    ],
    timeSaved: "Zekerheid dat er altijd iemand is die meedenkt en bijspringt",
    deliverables: [
      "Wekelijkse of tweewekelijkse afstemming — altijd op de hoogte van wat er speelt",
      "Productie support: directe beschikbaarheid bij blokkades, bugs of urgente zaken",
      "Innovatie begeleiding: implementatie van AI-initiatieven, technische keuzes, prompt engineering",
      "Business sparring: strategie, roadmap, prioriteiten en beslissingssupport",
      "Maandelijks overzicht: waar zijn de uren gevallen, wat is opgeleverd, wat staat er voor volgende maand",
    ],
  },
];
