import type { SlideConfig, Workflow } from "@/lib/types";

export const BRAND = {
  bg: "var(--brand-bg)",
  lime: "var(--brand-accent)",
  blue: "var(--brand-primary)",
  black: "var(--brand-fg)",
  muted: "#666666",
  border: "var(--brand-border)",
} as const;

export const AI_BUILD_NOTE =
  "Estimates reflect AI-assisted delivery — shorter timelines, fewer billable hours. Hosting and third-party licences excluded.";

export const workflows: Workflow[] = [
  {
    id: "WF0",
    title: "Secure AI Foundation",
    bucket: "Quick Win",
    reach: 10,
    impact: 3,
    impactLabel: "Massive",
    confidencePct: 100,
    effort: 1,
    riceReported: 30,
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    weeks: "1–1.5",
    effortDays: "5–8 days",
    investment: "€6–9k",
    summary:
      "Your own private AI environment — built for sensitive financial and client data.",
    why: "Public AI tools are not acceptable when you work with confidential fund, client and deal data. AB Capital needs AI that stays in Europe, uses only your data, and never trains on your information.",
    benefits: [
      "Work with sensitive data without leakage to US-based models",
      "Your documents stay yours — zero retention, EU-hosted",
      "Train and tune on your own frameworks, memos and policies over time",
      "One trusted layer for every AI workflow that follows",
    ],
    foundationFor: ["WF5 document automation", "WF7 legal & KYC", "WF8 deal flow & memos"],
    timeSaved: "Enabler — unlocks safe AI across the organisation",
    deliverables: [
      "Private AI environment (EU)",
      "Usage policies your team can trust",
      "Ready for deal, legal and ops automation",
    ],
  },
  {
    id: "WF5",
    title: "Fund Document Pipeline",
    bucket: "Quick Win",
    reach: 30,
    impact: 2.5,
    impactLabel: "High",
    confidencePct: 90,
    effort: 1.2,
    riceReported: 56,
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    weeks: "2",
    effortDays: "8–10 days",
    investment: "€8–12k",
    summary:
      "Stop manually renaming and uploading fund documents — the daily admin grind goes away.",
    why: "Capital calls, distributions and quarterly reports arrive constantly. One wrong filename breaks Bunch automations downstream. This is repetitive work nobody should be doing by hand.",
    benefits: [
      "Incoming docs land correctly named, every time",
      "Shared naming rules become the backbone for AI to read and route files",
      "Fewer errors that break fund admin workflows",
      "Immediate time back for the ops team every week",
    ],
    foundationFor: ["Cleaner data for WF3 reporting", "Reliable inputs for WF4 LP views"],
    timeSaved: "~6–10 hours/week fund administration",
    deliverables: [
      "Automatic intake & rename to Bunch conventions",
      "Staging for upload — no more download-rename-upload loops",
      "Naming standard documented for humans and AI",
    ],
  },
  {
    id: "WF8",
    title: "AI Deal Flow & Memo Suite",
    bucket: "Quick Win",
    reach: 15,
    impact: 3,
    impactLabel: "Massive",
    confidencePct: 80,
    effort: 2.5,
    riceReported: 14,
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    weeks: "4–6",
    effortDays: "18–25 days",
    investment: "€22–32k",
    summary:
      "From inbound opportunity to investment committee — faster, consistent, repeatable.",
    why: "Every deal is evaluated differently today. That slows IC prep and makes quality depend on who is available. You need a standard way to assess risk, map structures and produce memos.",
    benefits: [
      "Compare opportunities against your investment thesis — consistently",
      "Structure charts and cap tables profiled automatically",
      "First draft investment memos in hours, not days",
      "Better IC conversations with less prep friction",
    ],
    foundationFor: ["Requires WF0 secure AI foundation"],
    timeSaved: "~2–3 days per deal → memo draft in hours",
    deliverables: [
      "Thesis-based risk scoring",
      "Entity & cap table profiling",
      "Presentation-ready memo output",
    ],
  },
  {
    id: "WF1",
    title: "File & Asset Management",
    bucket: "Quick Win",
    reach: 40,
    impact: 2,
    impactLabel: "High",
    confidencePct: 90,
    effort: 2,
    riceReported: 36,
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    weeks: "3–4",
    effortDays: "12–16 days",
    investment: "€14–20k",
    summary:
      "One place for every file — no more hunting through inboxes and scattered folders.",
    why: "Critical documents live in personal inboxes and ad-hoc SharePoint folders. That creates knowledge silos and slows everyone down when something urgent comes up.",
    benefits: [
      "Find any client or fund file in seconds, not minutes",
      "Incoming PDFs routed to the right place automatically",
      "The whole office works from the same structure",
      "Less risk of outdated versions or lost documents",
    ],
    timeSaved: "~4–6 hours/week searching and filing",
    deliverables: [
      "Clear folder structure & governance",
      "Inbox-to-folder routing",
      "Metadata and version control",
    ],
  },
  {
    id: "WF7",
    title: "Legal & KYC Automation",
    bucket: "Quick Win",
    reach: 25,
    impact: 3,
    impactLabel: "Massive",
    confidencePct: 85,
    effort: 1.5,
    riceReported: 43,
    phaseOriginal: "NOW",
    phaseRevised: "NEXT",
    weeks: "3–4",
    effortDays: "12–16 days",
    investment: "€12–18k",
    summary:
      "Onboarding paperwork pre-filled from data you already have — legal review stays in control.",
    why: "Transfer agreements, UBO docs and W-8 forms involve repetitive typing nobody enjoys. It slows client onboarding and introduces errors.",
    benefits: [
      "Templates populated from existing client and fund records",
      "Faster onboarding without cutting legal corners",
      "Phase 1: two document types, human review built in",
      "Less manual work on work the team actively dislikes",
    ],
    foundationFor: ["Requires WF0 secure AI foundation"],
    timeSaved: "~4–8 hours per onboarding",
    deliverables: [
      "Two live document templates (phase 1)",
      "Auto-fill from existing records",
      "Review workflow before anything is sent",
    ],
  },
  {
    id: "WF9",
    title: "Website & Brand",
    bucket: "Quick Win",
    reach: 50,
    impact: 1,
    impactLabel: "Medium",
    confidencePct: 100,
    effort: 1.5,
    riceReported: 33,
    phaseOriginal: "NEXT",
    phaseRevised: "PARALLEL",
    weeks: "3–4",
    effortDays: "12–15 days",
    investment: "€12–18k",
    summary:
      "Update your site and content without waiting on developers.",
    why: "Marketing and brand updates currently depend on technical help. That slows campaigns and makes the public face of AB Capital harder to keep current.",
    benefits: [
      "Marketing team publishes pages and copy independently",
      "Modern, flexible site ready for future client portal ideas",
      "Faster campaign turnaround",
      "Runs in parallel — does not block ops automation work",
    ],
    timeSaved: "Content updates: days → hours",
    deliverables: [
      "Easy-to-use content management",
      "New site live with migrated content",
      "SEO-safe redirects",
    ],
  },
  {
    id: "WF3",
    title: "Investment Performance Insights",
    bucket: "Incremental",
    reach: 20,
    impact: 2.5,
    impactLabel: "High",
    confidencePct: 80,
    effort: 3,
    riceReported: 13,
    phaseOriginal: "NEXT",
    phaseRevised: "NEAR",
    weeks: "5–7",
    effortDays: "20–28 days",
    investment: "€24–34k",
    summary:
      "Client-ready portfolio views — without fighting rigid reporting tools.",
    why: "Quarterly reporting from Bunch and KRIF is painful to consolidate. Previous Power BI attempts did not give you the clarity or presentation quality you need.",
    benefits: [
      "Allocations across strategies, vintages and asset classes — one view",
      "AB-involved vs. non-AB performance clearly separated",
      "Something you are proud to show clients",
      "Less manual quarterly assembly",
    ],
    timeSaved: "~1–2 days per quarterly cycle",
    deliverables: [
      "Allocation dashboards",
      "Multi-vintage fund views",
      "Client-presentable reporting",
    ],
  },
  {
    id: "WF2",
    title: "Real-Time Financial Overview",
    bucket: "Incremental",
    reach: 40,
    impact: 2.5,
    impactLabel: "High",
    confidencePct: 60,
    effort: 4.5,
    riceReported: 13,
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    weeks: "8–10",
    effortDays: "35–45 days",
    investment: "€35–50k",
    summary:
      "See cash and expenses across 40 entities — live, not in yesterday's spreadsheet.",
    why: "Management still relies on reactive Excel updates across Twinfield and Basecone. Dutch GAAP constraints ruled out off-the-shelf ERP shortcuts.",
    benefits: [
      "Unified cash position without manual consolidation",
      "Line-item detail when decisions need it",
      "Less time chasing accountants for status updates",
      "Runway visibility for leadership",
    ],
    timeSaved: "~8–12 hours/week finance consolidation",
    deliverables: [
      "Live multi-entity dashboard",
      "Cash and expense views leadership can trust",
      "Built around your existing Twinfield setup",
    ],
  },
  {
    id: "WF4",
    title: "Limited Partner Dashboard",
    bucket: "Incremental",
    reach: 30,
    impact: 2,
    impactLabel: "High",
    confidencePct: 70,
    effort: 4,
    riceReported: 11,
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    weeks: "6–8",
    effortDays: "28–35 days",
    investment: "€28–40k",
    summary:
      "Instant view of LP positions, capital calls and fund performance.",
    why: "LP data sits across disconnected fund admin lines. Investor relations and fundraising prep take longer than they should.",
    benefits: [
      "One screen for LP structures and outstanding commitments",
      "Faster answers when LPs or prospects ask questions",
      "Stronger foundation for future fundraising",
      "Less manual assembly before every investor conversation",
    ],
    timeSaved: "~6–10 hours/week LP reporting",
    deliverables: [
      "LP position summary",
      "Capital call tracking",
      "Fund performance overview",
    ],
  },
  {
    id: "WF6",
    title: "Email-Driven Workflows",
    bucket: "Incremental",
    reach: 15,
    impact: 1.5,
    impactLabel: "Medium",
    confidencePct: 60,
    effort: 3.5,
    riceReported: 4,
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    weeks: "5–6",
    effortDays: "22–28 days",
    investment: "€18–26k",
    summary:
      "Important actions extracted from email — tracked in Notion without inbox archaeology.",
    why: "Operational tasks hide in shared and personal inboxes. Management alignment depends on manual check-ins and memory.",
    benefits: [
      "Key emails become trackable tasks automatically",
      "Less time reading threads to find what needs doing",
      "Shared visibility in Notion without inbox bottlenecks",
      "Fewer things falling through the cracks",
    ],
    timeSaved: "~3–5 hours/week management overhead",
    deliverables: [
      "Shared inbox monitoring",
      "Automatic task creation in Notion",
      "Clear ownership on extracted actions",
    ],
  },
  {
    id: "WF10",
    title: "Replace Bunch (Long-term)",
    bucket: "Big Bet",
    reach: 50,
    impact: 3,
    impactLabel: "Massive",
    confidencePct: 40,
    effort: 5,
    riceReported: 12,
    phaseOriginal: "BACKLOG",
    phaseRevised: "BACKLOG",
    weeks: "2–3 wk discovery",
    effortDays: "8–12 days discovery",
    investment: "€8–12k discovery · build TBD",
    summary:
      "Reduce €18–30k/fund/year vendor lock-in — but only after a clear build vs. buy decision.",
    why: "Bunch is expensive, rigid on APIs and forces manual workarounds. Full replacement is high friction — discovery first is the responsible path.",
    benefits: [
      "Understand true cost of staying vs. switching",
      "Roadmap before any big migration commitment",
      "Potential to reclaim significant annual software spend",
      "Full programmatic access to your own fund data long-term",
    ],
    timeSaved: "Structural — vendor cost + manual work reduction",
    deliverables: [
      "Build vs. buy recommendation",
      "Migration roadmap if justified",
      "ROI model per fund",
    ],
  },
];

export const riceSorted = [...workflows].sort(
  (a, b) => b.riceReported - a.riceReported,
);

export const phases = [
  {
    id: "now",
    label: "Phase 1 · NOW",
    period: "Weeks 1–4",
    invest: "€14–21k",
    headline: "Foundation & immediate ops wins",
    workflows: ["WF0", "WF5"],
    outcomes: [
      "Safe AI your team can use on sensitive data",
      "Daily fund document handling on autopilot",
      "Naming backbone ready for everything that follows",
    ],
  },
  {
    id: "next",
    label: "Phase 2 · NEXT",
    period: "Month 2–3",
    invest: "€48–70k",
    headline: "Structure, deal flow & onboarding",
    workflows: ["WF8", "WF1", "WF7"],
    outcomes: [
      "Faster path from opportunity to investment committee",
      "One file structure for the whole organisation",
      "Legal onboarding templates — phase 1 live",
    ],
  },
  {
    id: "parallel",
    label: "Parallel track",
    period: "Month 2–3",
    invest: "€12–18k",
    headline: "Brand & digital presence",
    workflows: ["WF9"],
    outcomes: [
      "Marketing updates without developer dependency",
      "Modern public-facing site",
      "Independent from ops roadmap timing",
    ],
  },
  {
    id: "near",
    label: "Phase 3 · NEAR",
    period: "Month 4+",
    invest: "€105–150k",
    headline: "Data platforms & long-term bets",
    workflows: ["WF3", "WF2", "WF4", "WF6", "WF10"],
    outcomes: [
      "Live finance & portfolio visibility",
      "LP investor portal",
      "Informed decision on Bunch replacement",
    ],
  },
] as const;

export const packages = [
  {
    name: "Foundation",
    tag: "Start small",
    workflows: "WF0 + WF5",
    weeks: "2–3",
    invest: "€14–21k",
    description:
      "Secure AI plus document automation — fast ROI, low risk, sets the backbone.",
  },
  {
    name: "Momentum",
    tag: "Recommended",
    workflows: "WF0 + WF5 + WF8 MVP",
    weeks: "6–8",
    invest: "€36–53k",
    description:
      "Foundation plus deal flow — ops efficiency and investment team impact together.",
    recommended: true,
  },
  {
    name: "Full Phase 1–2",
    tag: "Complete",
    workflows: "WF0–WF8 + WF1 + WF7 phase 1",
    weeks: "10–14",
    invest: "€74–108k",
    description:
      "Full NOW + NEXT roadmap including file governance and legal automation.",
  },
] as const;

export const wayOfWorking = [
  {
    title: "Discovery-led",
    body: "We start from your workshop findings — not a generic playbook. Scope is validated before build.",
  },
  {
    title: "AI-assisted delivery",
    body: "We build with AI — so you get working software faster and at a fraction of classic agency cost.",
  },
  {
    title: "Phased, not big bang",
    body: "Each phase delivers usable value before the next starts. You choose how far to go.",
  },
  {
    title: "Your data, your control",
    body: "Especially for AB Capital: private AI, EU hosting, no training on your confidential information.",
  },
] as const;

export const slideConfigs: SlideConfig[] = [
  { label: "Debrief", variant: "light" },
  { label: "Challenge", variant: "light" },
  { label: "Way of working", variant: "light" },
  { label: "Roadmap", variant: "light" },
  { label: "Phase 1", variant: "light" },
  { label: "Phase 2", variant: "light" },
  { label: "Phase 3", variant: "light" },
  { label: "Workflows", variant: "light" },
  { label: "Prioritisation", variant: "light" },
  { label: "Investment", variant: "light" },
  { label: "Next steps", variant: "light" },
];

export const slideLabels = slideConfigs.map((s) => s.label);

export function getWorkflow(id: string) {
  return workflows.find((w) => w.id === id);
}

export function getSlideVariant(index: number): "light" | "blue" {
  return slideConfigs[index]?.variant ?? "light";
}
