import type { WorkflowSource } from "@foundation/types";

/**
 * AB Capital workflow definitions: bron van waarheid voor RICE + kosten.
 * Narratieve content staat hier; investeringstotalen voor fases/pakketten worden berekend.
 */
export const workflowSources: WorkflowSource[] = [
  {
    id: "WF0",
    title: "Veilig AI-fundament",
    bucket: "Quick Win",
    rice: { reach: 10, impact: 3, confidencePct: 100, effort: 1 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 5, daysMax: 8, weeks: "1–1.5", daysLabel: "5–8 dagen" },
    cost: { min: 6000, max: 9000 },
    summary:
      "Een eigen private AI-omgeving, gebouwd voor gevoelige financiële en klantdata.",
    why: "Publieke AI-tools zijn niet acceptabel wanneer je werkt met vertrouwelijke fonds-, klant- en dealdata. AB Capital heeft AI nodig die in Europa blijft, alleen jullie data gebruikt en nooit op jullie informatie traint.",
    benefits: [
      "Werk met gevoelige data zonder lekken naar US-modellen",
      "Jullie documenten blijven van jullie: zero retention, EU-hosted",
      "Train en tune op eigen frameworks, memo's en policies",
      "Eén vertrouwde laag voor elke AI-workflow die volgt",
    ],
    foundationFor: ["WF5 documentautomatisering", "WF7 legal & KYC", "WF8 deal flow & memo's"],
    timeSaved: "Enabler: ontgrendelt veilige AI in de hele organisatie",
    deliverables: [
      "Private AI-omgeving (EU)",
      "Gebruiksrichtlijnen waar het team op kan vertrouwen",
      "Klaar voor deal-, legal- en ops-automatisering",
    ],
  },
  {
    id: "WF5",
    title: "Fondsdocument-pipeline",
    bucket: "Quick Win",
    rice: { reach: 30, impact: 2.5, confidencePct: 90, effort: 1.2 },
    impactLabel: "High",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 8, daysMax: 10, weeks: "2", daysLabel: "8–10 dagen" },
    cost: { min: 8000, max: 12000 },
    summary:
      "Stop met handmatig hernoemen en uploaden van fondsdocumenten. De dagelijkse admin verdwijnt.",
    why: "Capital calls, distributies en kwartaalrapporten komen constant binnen. Eén verkeerde bestandsnaam breekt Bunch-automatiseringen downstream. Dit is repetitief werk dat niemand handmatig zou moeten doen.",
    benefits: [
      "Inkomende docs landen elke keer correct benoemd",
      "Gedeelde naamgevingsregels worden de backbone voor AI om bestanden te lezen en routeren",
      "Minder fouten die fund admin-workflows breken",
      "Direct tijd terug voor het ops-team, elke week",
    ],
    foundationFor: ["Schonere data voor WF3 reporting", "Betrouwbare input voor WF4 LP-views"],
    timeSaved: "~6–10 uur/week fund administration",
    deliverables: [
      "Automatische intake en rename naar Bunch-conventies",
      "Staging voor upload: geen download-rename-upload loops meer",
      "Naamgevingsstandaard gedocumenteerd voor mens en AI",
    ],
  },
  {
    id: "WF8",
    title: "AI Deal Flow & Memo Suite",
    bucket: "Quick Win",
    rice: { reach: 15, impact: 3, confidencePct: 80, effort: 2.5 },
    impactLabel: "Massive",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 18, daysMax: 25, weeks: "4–6", daysLabel: "18–25 dagen" },
    cost: { min: 22000, max: 32000 },
    summary:
      "Van binnenkomende opportunity naar investment committee: sneller, consistent, herhaalbaar.",
    why: "Elke deal wordt vandaag anders geëvalueerd. Dat vertraagt IC-voorbereiding en maakt kwaliteit afhankelijk van wie beschikbaar is. Jullie hebben een standaard manier nodig om risico te beoordelen, structuren te mappen en memo's te produceren.",
    benefits: [
      "Vergelijk opportunities consistent met jullie investment thesis",
      "Structure charts en cap tables automatisch geprofileerd",
      "Eerste versie investment memo's in uren, niet dagen",
      "Betere IC-gesprekken met minder prep-frictie",
    ],
    foundationFor: ["Vereist WF0 veilig AI-fundament"],
    timeSaved: "~2–3 dagen per deal naar memo-draft in uren",
    deliverables: [
      "Thesis-based risk scoring",
      "Entity- en cap table-profiling",
      "Presentation-ready memo-output",
    ],
  },
  {
    id: "WF1",
    title: "File & Asset Management",
    bucket: "Quick Win",
    rice: { reach: 40, impact: 2, confidencePct: 90, effort: 2 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 12, daysMax: 16, weeks: "3–4", daysLabel: "12–16 dagen" },
    cost: { min: 14000, max: 20000 },
    summary: "Eén plek voor elk bestand. Geen zoeken meer in inboxen en verspreide mappen.",
    why: "Kritieke documenten leven in persoonlijke inboxen en ad-hoc SharePoint-mappen. Dat creëert kennissilo's en vertraagt iedereen wanneer iets urgent opduikt.",
    benefits: [
      "Vind elk klant- of fondsbestand in seconden, niet minuten",
      "Inkomende PDF's automatisch naar de juiste plek gerouteerd",
      "Het hele kantoor werkt vanuit dezelfde structuur",
      "Minder risico op verouderde versies of verloren documenten",
    ],
    timeSaved: "~4–6 uur/week zoeken en archiveren",
    deliverables: [
      "Heldere mapstructuur en governance",
      "Inbox-naar-map routing",
      "Metadata en version control",
    ],
  },
  {
    id: "WF7",
    title: "Legal & KYC-automatisering",
    bucket: "Quick Win",
    rice: { reach: 25, impact: 3, confidencePct: 85, effort: 1.5 },
    impactLabel: "Massive",
    phaseOriginal: "NOW",
    phaseRevised: "NEXT",
    effort: { daysMin: 12, daysMax: 16, weeks: "3–4", daysLabel: "12–16 dagen" },
    cost: { min: 12000, max: 18000 },
    summary:
      "Onboardingpapierwerk vooringevuld vanuit data die jullie al hebben. Juridische review blijft in control.",
    why: "Transfer agreements, UBO-docs en W-8-formulieren betekenen repetitief typwerk dat niemand leuk vindt. Het vertraagt klant-onboarding en introduceert fouten.",
    benefits: [
      "Templates gevuld vanuit bestaande klant- en fondsrecords",
      "Snellere onboarding zonder juridische corners af te snijden",
      "Fase 1: twee documenttypes, menselijke review ingebouwd",
      "Minder handmatig werk aan taken die het team actief vermijdt",
    ],
    foundationFor: ["Vereist WF0 veilig AI-fundament"],
    timeSaved: "~4–8 uur per onboarding",
    deliverables: [
      "Twee live documenttemplates (fase 1)",
      "Auto-fill vanuit bestaande records",
      "Review-workflow vóór verzending",
    ],
  },
  {
    id: "WF9",
    title: "Website & merk",
    bucket: "Quick Win",
    rice: { reach: 50, impact: 1, confidencePct: 100, effort: 1.5 },
    impactLabel: "Medium",
    phaseOriginal: "NEXT",
    phaseRevised: "PARALLEL",
    effort: { daysMin: 12, daysMax: 15, weeks: "3–4", daysLabel: "12–15 dagen" },
    cost: { min: 12000, max: 18000 },
    summary: "Update jullie site en content zonder op developers te wachten.",
    why: "Marketing- en merkupdates hangen nu af van technische hulp. Dat vertraagt campagnes en maakt de publieke face van AB Capital lastiger actueel te houden.",
    benefits: [
      "Marketingteam publiceert pagina's en copy zelfstandig",
      "Moderne, flexibele site klaar voor toekomstige client portal-ideeën",
      "Snellere campagne-doorlooptijd",
      "Loopt parallel: blokkeert ops-automatisering niet",
    ],
    timeSaved: "Contentupdates: dagen naar uren",
    deliverables: [
      "Gebruiksvriendelijk content management",
      "Nieuwe site live met gemigreerde content",
      "SEO-veilige redirects",
    ],
  },
  {
    id: "WF3",
    title: "Investment Performance Insights",
    bucket: "Incremental",
    rice: { reach: 20, impact: 2.5, confidencePct: 80, effort: 3 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEAR",
    effort: { daysMin: 20, daysMax: 28, weeks: "5–7", daysLabel: "20–28 dagen" },
    cost: { min: 24000, max: 34000 },
    summary: "Client-ready portfolio-views, zonder te vechten met rigide reportingtools.",
    why: "Kwartaalrapportage uit Bunch en KRIF is pijnlijk te consolideren. Eerdere Power BI-pogingen gaven niet de helderheid of presentatiekwaliteit die jullie nodig hebben.",
    benefits: [
      "Allocaties over strategieën, vintages en asset classes in één view",
      "AB-betrokken vs. niet-AB performance duidelijk gescheiden",
      "Iets waar jullie trots mee naar klanten kunnen",
      "Minder handmatige kwartaalassemblage",
    ],
    timeSaved: "~1–2 dagen per kwartaalcyclus",
    deliverables: [
      "Allocatie-dashboards",
      "Multi-vintage fund views",
      "Client-presentable reporting",
    ],
  },
  {
    id: "WF2",
    title: "Real-time financieel overzicht",
    bucket: "Incremental",
    rice: { reach: 40, impact: 2.5, confidencePct: 60, effort: 4.5 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 35, daysMax: 45, weeks: "8–10", daysLabel: "35–45 dagen" },
    cost: { min: 35000, max: 50000 },
    summary: "Zie cash en expenses over 40 entiteiten live, niet in de spreadsheet van gisteren.",
    why: "Management leunt nog op reactieve Excel-updates over Twinfield en Basecone. Nederlandse GAAP-beperkingen sloten off-the-shelf ERP-shortcuts uit.",
    benefits: [
      "Geünificeerde cashpositie zonder handmatige consolidatie",
      "Line-item detail wanneer beslissingen dat nodig hebben",
      "Minder tijd achter accountants aan voor statusupdates",
      "Runway-zichtbaarheid voor leadership",
    ],
    timeSaved: "~8–12 uur/week finance-consolidatie",
    deliverables: [
      "Live multi-entity dashboard",
      "Cash- en expense-views waar leadership op kan vertrouwen",
      "Gebouwd rond jullie bestaande Twinfield-setup",
    ],
  },
  {
    id: "WF4",
    title: "Limited Partner Dashboard",
    bucket: "Incremental",
    rice: { reach: 30, impact: 2, confidencePct: 70, effort: 4 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 28, daysMax: 35, weeks: "6–8", daysLabel: "28–35 dagen" },
    cost: { min: 28000, max: 40000 },
    summary: "Direct zicht op LP-posities, capital calls en fondsperformance.",
    why: "LP-data zit verspreid over losgekoppelde fund admin-lijnen. Investor relations en fundraising-prep duren langer dan nodig.",
    benefits: [
      "Eén scherm voor LP-structuren en openstaande commitments",
      "Snellere antwoorden wanneer LPs of prospects vragen stellen",
      "Sterkere basis voor toekomstige fundraising",
      "Minder handmatige assemblage vóór elk investeerdersgesprek",
    ],
    timeSaved: "~6–10 uur/week LP-reporting",
    deliverables: [
      "LP-positieoverzicht",
      "Capital call-tracking",
      "Fondsperformance-overzicht",
    ],
  },
  {
    id: "WF6",
    title: "Email-gedreven workflows",
    bucket: "Incremental",
    rice: { reach: 15, impact: 1.5, confidencePct: 60, effort: 3.5 },
    impactLabel: "Medium",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 22, daysMax: 28, weeks: "5–6", daysLabel: "22–28 dagen" },
    cost: { min: 18000, max: 26000 },
    summary:
      "Belangrijke acties uit e-mail geëxtraheerd en getrackt in Notion, zonder inbox-archeologie.",
    why: "Operationele taken verstoppen zich in gedeelde en persoonlijke inboxen. Management-alignment hangt af van handmatige check-ins en geheugen.",
    benefits: [
      "Belangrijke e-mails worden automatisch trackbare taken",
      "Minder tijd aan threads lezen om te vinden wat gedaan moet worden",
      "Gedeeld zicht in Notion zonder inbox-bottlenecks",
      "Minder dingen die door de mazen glippen",
    ],
    timeSaved: "~3–5 uur/week management overhead",
    deliverables: [
      "Monitoring van gedeelde inbox",
      "Automatische taakaanmaak in Notion",
      "Duidelijke ownership op geëxtraheerde acties",
    ],
  },
  {
    id: "WF10",
    title: "Bunch vervangen (langetermijn)",
    bucket: "Big Bet",
    rice: { reach: 50, impact: 3, confidencePct: 40, effort: 5 },
    impactLabel: "Massive",
    phaseOriginal: "BACKLOG",
    phaseRevised: "BACKLOG",
    effort: { daysMin: 8, daysMax: 12, weeks: "2–3 wk discovery", daysLabel: "8–12 dagen discovery" },
    cost: { min: 8000, max: 12000 },
    summary:
      "Minder vendor lock-in, maar pas na een heldere build vs. buy-beslissing.",
    why: "Bunch is duur, rigide op API's en dwingt tot handmatige workarounds. Volledige vervanging heeft hoge frictie; discovery eerst is het verantwoorde pad.",
    benefits: [
      "Begrijp de echte kosten van blijven vs. switchen",
      "Roadmap vóór elke grote migratiecommitment",
      "Potentieel om aanzienlijke jaarlijkse softwarekosten terug te winnen",
      "Volledige programmatische toegang tot eigen fondsdata op lange termijn",
    ],
    timeSaved: "Structureel: vendor-kosten plus minder handmatig werk",
    deliverables: [
      "Build vs. buy-aanbeveling",
      "Migratieroadmap indien gerechtvaardigd",
      "ROI-model per fonds",
    ],
  },
];
