import type { WorkflowSource } from "@foundation/types";

export const workflowSourcesNl: WorkflowSource[] = [
  {
    id: "WF1",
    title: "TikTok Content & UGC Workflow",
    bucket: "Quick Win",
    rice: { reach: 8, impact: 2, confidencePct: 85, effort: 4 },
    impactLabel: "High",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 20, daysMax: 35, weeks: "6–10 weken", daysLabel: "20–35 dagen" },
    cost: { min: 8000, max: 20000 },
    investmentLabel: "€8K–€20K",
    hideTimeline: true,
    summary:
      "Een schaalbare contentmachine voor TikTok, Meta en short-form kanalen — via UGC, micro-influencers en een gestroomlijnde productieworkflow.",
    why: "85% van de orders komt via Meta. Afhankelijkheid van één kanaal is een groeirisico. TikTok biedt een schaalbare manier om nieuwe doelgroepen te bereiken, maar vereist structurele contentcapaciteit die Zappiebox nu mist. Bestaande agencies worden als te duur ervaren; een zelfbeheerde UGC-workflow is het schaalbare alternatief.",
    benefits: [
      "Minder Meta-afhankelijkheid via een tweede schaalbaar acquisitiekanaal",
      "Lagere contentproductiekosten door gestructureerde UGC en micro-influencer workflows",
      "Herbruikbare content voor Meta, YouTube Shorts en TikTok vanuit één productierun",
    ],
    timeSaved: "Van ad-hoc contentproductie naar een herhaalbare, schaalbare UGC-machine",
    deliverables: [
      "Contentstrategie voor TikTok en short-form kanalen",
      "Contentformaten: hooks, storytelling formats, UGC-briefs",
      "UGC-workflow: selectiecriteria creators, briefingtemplates, review- en goedkeuringsproces",
      "Micro-influencer shortlist en onboarding aanpak",
      "Contentkalender en productieplanning",
      "Organische TikTok-content: eerste batch posts",
      "Advertentievarianten voor TikTok en hergebruik op Meta",
      "Rapportageframework voor creative performance",
      "Workflow voor verzamelen en hergebruiken van klantcontent",
      "Testplan: statics vs video, organisch vs betaald",
    ],
  },
  {
    id: "WF2",
    title: "SEO & AEO Growth Engine",
    bucket: "Big Bet",
    rice: { reach: 9, impact: 2, confidencePct: 80, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weken", daysLabel: "25–45 dagen" },
    cost: { min: 12000, max: 30000 },
    investmentLabel: "€12K–€30K",
    hideTimeline: true,
    summary:
      "Structureel organisch verkeer opbouwen via SEO en AEO — de afhankelijkheid van betaald Meta-verkeer verminderen en ouders, scholen en kinderopvang bereiken via zoekmachines.",
    why: "Zappiebox wil nadrukkelijk investeren in organische groei en minder afhankelijk worden van Meta. Een sterk SEO- en AEO-fundament is de basis voor duurzame, kostenefficiënte acquisitie die aanwast in de tijd. AEO zorgt voor zichtbaarheid in AI-gedreven zoekresultaten waar ouders steeds vaker advies zoeken.",
    benefits: [
      "Organisch verkeer dat groeit zonder extra mediabudget",
      "Zichtbaarheid in AI-zoekresultaten (ChatGPT, Perplexity, Google AI Overviews)",
      "Ouders bereiken die zoeken op abonnementsboxen, cadeau-ideeën en kindontwikkeling",
    ],
    timeSaved: "Van Meta-afhankelijkheid naar duurzame organische acquisitie die aanwast in de tijd",
    deliverables: [
      "SEO-audit: technisch, on-page en contenthiaten",
      "Zoekwoordenonderzoek: zoekopdrachten van ouders, scholen, kinderopvang en cadeaugevers",
      "Contentclusterstrategie en redactionele kalender",
      "Landingspagina-copy en -structuur per doelgroep",
      "Blog- en gidscontent: eerste batch artikelen",
      "Interne linkstructuur en breadcrumb-implementatie",
      "Structured data (JSON-LD) voor product, FAQ en organisatie",
      "AEO-optimalisatie: content gestructureerd voor AI-antwoordmachines",
      "Contentproductieworkflow (eventueel met AI-ondersteunde pipeline)",
      "Meetplan en maandelijkse SEO-performancerapportage",
    ],
  },
  {
    id: "WF3",
    title: "CRO & Doelgroepgerichte Landingpages",
    bucket: "Quick Win",
    rice: { reach: 9, impact: 2, confidencePct: 85, effort: 5 },
    impactLabel: "High",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 20, daysMax: 35, weeks: "6–10 weken", daysLabel: "20–35 dagen" },
    cost: { min: 10000, max: 25000 },
    investmentLabel: "€10K–€25K",
    hideTimeline: true,
    summary:
      "Conversieratio verbeteren en advertentieverkeer beter laten aansluiten op specifieke doelgroepen, proposities en campagnes via gerichte landingspagina's en gestructureerde A/B-tests.",
    why: "De conversieratio is gegroeid van 1,8% naar 2,1%, maar structurele experimentatie is beperkt. Zappiebox noemt zelf persona-specifieke landingspagina's, campagnepagina's en dynamische content als directe kansen. Betere aansluiting tussen advertentie en pagina levert doorgaans sneller rendement dan meer mediabudget.",
    benefits: [
      "Meer omzet uit hetzelfde mediabudget via hogere conversie",
      "Betere advertentie-paginafit voor ouders, cadeaugevers, scholen en buitenlandse bezoekers",
      "Een gestructureerd A/B-testbacklog dat performance blijft verbeteren",
    ],
    timeSaved: "Van generiek homepage-verkeer naar maatwerk landingservaringen per doelgroep en campagne",
    deliverables: [
      "CRO-audit: funnelanalyse, Shopify-data, heatmaps en sessie-opnames",
      "Persona-mapping: ouders, cadeaugevers, scholen, Duitse bezoekers, seizoensgebonden doelgroepen",
      "Landingspagina-templateontwerp (UX/UI) geoptimaliseerd voor conversie",
      "Doelgroepspecifieke pagina's: copywriting en Shopify-implementatie",
      "Campagne- en seizoensgebonden landingspagina's",
      "A/B-testplan met hypotheses, prioriteiten en meetcriteria",
      "Tracking-setup: eventdefinities, funnelevents en conversiedoelen",
      "Testbacklog voor doorlopend CRO-programma",
      "Rapportagedashboard voor landingspagina- en testperformance",
    ],
  },
  {
    id: "WF4",
    title: "Marketing Data & Performance Dashboard",
    bucket: "Big Bet",
    rice: { reach: 7, impact: 2, confidencePct: 70, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weken", daysLabel: "25–45 dagen" },
    cost: { min: 15000, max: 35000 },
    investmentLabel: "€15K–€35K",
    hideTimeline: true,
    summary:
      "Betere beslissingen mogelijk maken over kanalen, campagnes, creatives, abonnementen en klantwaarde via een centraal performance-dashboard — gebouwd naast de bestaande trackingpartner.",
    why: "Er is onvoldoende betrouwbare data om sterke conclusies per kanaal en creative te trekken. Zonder een datafundament zijn investeringsbeslissingen gebaseerd op aannames. Een centraal dashboard vertaalt ruwe data naar bruikbare inzichten over CAC, LTV, ROAS, cohorten en abonnementsretentie.",
    benefits: [
      "Datagedreven beslissingen over kanaal- en creative-investeringen",
      "Inzicht in CAC, LTV, ROAS en terugverdientermijn per kanaal",
      "Zicht op abonnementsretentie en churn om onvrijwillige uitval te verminderen",
    ],
    timeSaved: "Van buikgevoel-investeringsbeslissingen naar bewijs-gebaseerde kanaal- en creative-optimalisatie",
    deliverables: [
      "Inventarisatie databronnen en review trackingarchitectuur",
      "Afstemming met de bestaande trackingpartner om overlap te voorkomen",
      "KPI-framework: definities voor CAC, LTV, ROAS, terugverdientermijn, churn",
      "Kanaalrapportage: spend, omzet en ROAS per kanaal",
      "Creative-performance dashboard: hooks, formats en doelgroepuitsplitsing",
      "Cohortanalyse: abonnementsomzet en retentie per acquisitiecohort",
      "Abonnementsanalyse: prepaid vs periodiek, churntriggers, levenscyclusfases",
      "Dashboarddesign en BI-implementatie",
      "Datakwaliteitschecks en monitoring",
      "Rapportageritme en besliskaders voor media-investeringen",
    ],
  },
  {
    id: "WF5",
    title: "YouTube Ads Pilot",
    bucket: "Quick Win",
    rice: { reach: 6, impact: 1, confidencePct: 75, effort: 3 },
    impactLabel: "Medium",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 15, daysMax: 25, weeks: "4–8 weken", daysLabel: "15–25 dagen" },
    cost: { min: 7500, max: 17500 },
    investmentLabel: "€7.5K–€17.5K",
    hideTimeline: true,
    summary:
      "YouTube als aanvullend betaald kanaal testen in een afgebakende pilot — bestaande content hergebruikend, zonder direct een volledige organische YouTube-strategie te ontwikkelen.",
    why: "Zappiebox twijfelt over organische YouTube-content vanwege productiecapaciteit, maar ziet betaalde advertenties als kans. Een afgebakende pilot met hergebruikte UGC beperkt het risico en levert concreet bewijs of YouTube Ads zinvol zijn voordat grotere budgetten worden ingezet.",
    benefits: [
      "Laagdrempelig kanaaltest met bestaande of hergebruikte UGC-content",
      "Ouders bereiken in een discovery-mindset op YouTube",
      "Data voor toekomstige YouTube-investeringsbeslissingen",
    ],
    timeSaved: "Van kanaalcontext naar bewijs-gebaseerde YouTube-investeringsbeslissingen",
    deliverables: [
      "YouTube Ads-strategie en doelgroepselectie",
      "Campagnestructuur: awareness, overweging en retargeting",
      "Scriptontwikkeling voor 6s, 15s en 30s formaten",
      "Videocreative-productie of hergebruik van bestaande UGC",
      "Creative-testplan over formaten en boodschappen",
      "Tracking- en meetsetup voor YouTube-attributie",
      "Pilotcampagne setup en lancering",
      "Performanceevaluatie en go/no-go-aanbeveling",
    ],
    investmentNote: "Aanbevolen testmediabudget: €10K–€25K (separaat van deze investering)",
  },
  {
    id: "WF6",
    title: "B2B Partnership Propositie",
    bucket: "Big Bet",
    rice: { reach: 5, impact: 2, confidencePct: 65, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 40, weeks: "8–12 weken", daysLabel: "25–40 dagen" },
    cost: { min: 15000, max: 35000 },
    investmentLabel: "€15K–€35K",
    hideTimeline: true,
    summary:
      "Een herhaalbaar commercieel model ontwikkelen voor scholen, kinderopvangorganisaties en andere zakelijke partners — gevalideerd via een gestructureerde pilot vóór schaling.",
    why: "Partnerships met scholen en kinderopvang worden expliciet als groeikans benoemd. De exacte propositie, prijsstructuur en commerciële aanpak zijn echter nog niet gevalideerd. Gestructureerde propositie-ontwikkeling en een pilot voorkomen dat er in salesinfrastructuur wordt geïnvesteerd vóór bewezen vraag.",
    benefits: [
      "Een nieuw acquisitiekanaal onafhankelijk van Meta en organisch zoeken",
      "Schaalbaar model voor terugkerende B2B-relaties",
      "Gevalideerde commerciële propositie vóór investering in B2B-website of CRM",
    ],
    timeSaved: "Van ongetoetst B2B-idee naar een gevalideerde propositie met eerste betalende partners",
    deliverables: [
      "Markt- en segmentonderzoek: scholen, kinderopvang, zakelijke cadeaus",
      "Waardepropositie-ontwerp per segment",
      "Partnershipmodel-opties: bulkbestellingen, abonnementen, cadeau-programma's",
      "Prijs- en kortingsstructuur",
      "Salesmaterialen: pitchdeck, one-pager, e-mailtemplates",
      "Selectiecriteria pilotpartners en outreach-aanpak",
      "Partner-onboardingproces",
      "KPI's voor propositevalidatie",
      "Pilotuitvoering en evaluatierapport met go/no-go-aanbeveling",
    ],
  },
  {
    id: "WF7",
    title: "B2B Website of Subdomein",
    bucket: "Incremental",
    rice: { reach: 5, impact: 1, confidencePct: 60, effort: 6 },
    impactLabel: "Medium",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weken", daysLabel: "25–45 dagen" },
    cost: { min: 12000, max: 30000 },
    investmentLabel: "€12K–€30K",
    hideTimeline: true,
    summary:
      "Een aparte digitale omgeving voor zakelijke doelgroepen, partnerships en leadgeneratie — uitsluitend gebouwd nadat de B2B-propositie is gevalideerd.",
    why: "Zodra de B2B-propositie (WF6) is gevalideerd, ontbreekt een gerichte digitale omgeving voor zakelijke klanten. Een uitgebreide B2B-website bouwen vóór een bewezen salesmodel riskeert aanzienlijke investering met onzeker rendement. We adviseren dit project in fase 3.",
    benefits: [
      "Professionele digitale aanwezigheid voor zakelijke en institutionele kopers",
      "Leadcapture en -nurturing voor scholen, kinderopvang en zakelijke partners",
      "Scheiding van B2C- en B2B-boodschappen voor betere conversie",
    ],
    timeSaved: "Van ontbrekende B2B-digitale aanwezigheid naar een gerichte conversieomgeving voor zakelijke klanten",
    deliverables: [
      "Informatiearchitectuur voor B2B-omgeving",
      "B2B-propositie copy en messaging",
      "UX/UI-design voor landingspagina's, productpagina's en leadformulieren",
      "Cases en partnerinformatie",
      "Leadformulier-design en CRM-integratie",
      "Analytics en conversietracking",
      "Implementatie binnen Shopify of als apart subdomein",
    ],
  },
  {
    id: "WF8",
    title: "CRM voor Partnerships en Fysieke Kanalen",
    bucket: "Incremental",
    rice: { reach: 4, impact: 2, confidencePct: 50, effort: 7 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 30, daysMax: 55, weeks: "10–18 weken", daysLabel: "30–55 dagen" },
    cost: { min: 15000, max: 40000 },
    investmentLabel: "€15K–€40K",
    hideTimeline: true,
    summary:
      "Leads, scholen, kinderopvangorganisaties, partners en fysieke verkoopkanalen centraal beheren — zodra de B2B-activiteit voldoende volume bereikt voor gestructureerd CRM.",
    why: "Zodra het B2B-kanaal tractie krijgt, wordt leadbeheer in spreadsheets onschaalbaar. Een CRM voorkomt dat kansen verloren gaan. We adviseren licht te beginnen en pas op te schalen wanneer het B2B-pipeline-volume dit rechtvaardigt.",
    benefits: [
      "Geen leads of partnerships verloren door gebrek aan opvolgstructuur",
      "Duidelijk pipeline-overzicht voor B2B-salesactiviteit",
      "Fundament voor automatisering van partnercommunicatie en rapportage",
    ],
    timeSaved: "Van spreadsheet-gebaseerd partnerbeheer naar gestructureerde pipeline en opvolging",
    deliverables: [
      "CRM-selectieadvies op basis van eisen en pipeline-volume",
      "Procesontwerp: leadstatussen, contact- en organisatiemodel",
      "Pipeline-inrichting met statusdefinities en eigenaarschap",
      "Taak- en opvolgworkflow configuratie",
      "E-mail- en formulierIntegraties",
      "Automatiseringen voor veelvoorkomende workflows",
      "Rapportagedashboards voor pipeline- en partneractivity",
      "Training en documentatie",
    ],
  },
  {
    id: "WF9",
    title: "Duitsland Validatiepilot",
    bucket: "Big Bet",
    rice: { reach: 7, impact: 2, confidencePct: 45, effort: 8 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 35, daysMax: 65, weeks: "12–20 weken", daysLabel: "35–65 dagen" },
    cost: { min: 20000, max: 50000 },
    investmentLabel: "€20K–€50K",
    hideTimeline: true,
    summary:
      "Een lokale Duitse marktbenadering valideren die verder gaat dan vertaalde advertenties — via onderzoek, gelokaliseerde creative en een afgebakende pilotcampagne.",
    why: "Alleen advertenties vertalen blijkt onvoldoende voor de Duitse markt met andere positioneringsverwachtingen, concurrentiedynamiek en culturele nuances. Tegelijkertijd beperken cashflow en de huidige marketingvolwassenheid directe expansie. Een gestructureerde validatiepilot levert een go/no-go-beslissing vóór significante middelencommittering.",
    benefits: [
      "Een data-gedreven go/no-go-beslissing voor Duitsland vóór grootschalige investering",
      "Lokale creative en positionering getest onder echte marktomstandigheden",
      "Fundament voor volledige Nederlandse marktlancering als de pilot valideert",
    ],
    timeSaved: "Van veronderstelde marktfit naar gevalideerde Duitse groeistrategie",
    deliverables: [
      "Duits markt- en concurrentieonderzoek",
      "Lokale positionering en waardepropositie",
      "Culturele lokalisatie: copy, aanbod, beeldtaal",
      "Duitse advertentiecreative (statisch, video, UGC)",
      "Duitse landingspagina's met gelokaliseerde conversiecode",
      "Prijs- en aanbodtesten voor Duits publiek",
      "Kanaalstrategie: Meta, Google, TikTok voor Duitsland",
      "Pilotcampagne setup en uitvoering",
      "CRO en performancetracking voor Duits verkeer",
      "Pilotevaluatierapport met go/no-go-aanbeveling",
    ],
    investmentNote: "Een volledige marktlancering in Duitsland vereist separaat €50K–€100K+",
  },
  {
    id: "WF10",
    title: "Headless Shopify Rebuild",
    bucket: "Incremental",
    rice: { reach: 6, impact: 1, confidencePct: 30, effort: 10 },
    impactLabel: "Medium",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 65, daysMax: 140, weeks: "24–52 weken", daysLabel: "65–140 dagen" },
    cost: { min: 60000, max: 150000 },
    investmentLabel: "€60K–€150K",
    hideTimeline: true,
    summary:
      "Een nieuwe headless commerce-architectuur op basis van Shopify — met grotere flexibiliteit en performancepotentieel. Niet aanbevolen als prioriteit in dit stadium.",
    why: "Het huidige Shopify-theme beheerd door een freelancer laat geen duidelijke technische bottlenecks zien die een headless rebuild vereisen. Een headless migratie brengt zeer hoge effort, kosten en migratierisico zonder aangetoond commercieel of technisch probleem. We adviseren dit project voorlopig niet totdat concrete beperkingen zijn bewezen.",
    benefits: [
      "Volledige controle over front-end performance en UX",
      "Ontkoppelde architectuur voor toekomstige schaalbaarheid",
      "Mogelijkheden voor custom checkout en abonnementsflow",
    ],
    timeSaved: "Potentieel: van freelancer-beheerd theme naar volledig custom commerce-architectuur",
    deliverables: [
      "Technische discovery en architectuurontwerp",
      "UX/UI-design voor nieuwe front-end",
      "Front-end ontwikkeling (Next.js of vergelijkbaar)",
      "Shopify Storefront API-integratie",
      "CMS-integratie",
      "Analytics- en trackingmigratie",
      "SEO-migratieplan en -uitvoering",
      "Checkout- en Firmhouse-integratie",
      "QA, performancetesten en lancering",
      "Beheerdocumentatie",
    ],
  },
];
