import type { WorkflowSource } from "@foundation/types";

export const workflowSources: WorkflowSource[] = [
  {
    id: "WF1",
    title: "TikTok Content & UGC Workflow",
    bucket: "Quick Win",
    rice: { reach: 8, impact: 2, confidencePct: 85, effort: 4 },
    impactLabel: "High",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 20, daysMax: 35, weeks: "6–10 weeks", daysLabel: "20–35 days" },
    cost: { min: 8000, max: 20000 },
    investmentLabel: "€8K–€20K",
    hideTimeline: true,
    summary:
      "A scalable content machine for TikTok, Meta and short-form channels — via UGC, micro-influencers and a streamlined production workflow.",
    why: "85% of orders come via Meta. Dependency on a single channel is a growth risk. TikTok offers a scalable way to reach new audiences, but requires structural content capacity that Zappiebox currently lacks. Existing agencies are experienced as too expensive; a self-managed UGC workflow is the scalable alternative.",
    benefits: [
      "Reduced Meta dependency via a second scalable acquisition channel",
      "Lower content production cost through structured UGC and micro-influencer workflows",
      "Reusable content for Meta, YouTube Shorts and TikTok from a single production run",
    ],
    timeSaved: "From ad-hoc content production to a repeatable, scalable UGC machine",
    deliverables: [
      "Content strategy for TikTok and short-form channels",
      "Content format development: hooks, storytelling formats, UGC briefs",
      "UGC workflow: creator selection criteria, briefing templates, review and approval process",
      "Micro-influencer shortlist and onboarding approach",
      "Content calendar and production planning",
      "Organic TikTok content: first batch of posts",
      "Ad variants for TikTok and Meta repurposing",
      "Creative performance reporting framework",
      "Workflow for collecting and repurposing customer content",
      "Test plan: static vs video, organic vs paid",
    ],
  },
  {
    id: "WF2",
    title: "SEO & AEO Growth Engine",
    bucket: "Big Bet",
    rice: { reach: 9, impact: 2, confidencePct: 80, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weeks", daysLabel: "25–45 days" },
    cost: { min: 12000, max: 30000 },
    investmentLabel: "€12K–€30K",
    hideTimeline: true,
    summary:
      "Build structural organic traffic through SEO and AEO — reducing dependency on paid Meta acquisition and reaching parents, schools and childcare organisations through search.",
    why: "Zappiebox explicitly wants to invest in organic growth and reduce Meta dependency. A strong SEO and AEO foundation is the basis for durable, cost-efficient acquisition that compounds over time. AEO (Answer Engine Optimisation) ensures visibility in AI-driven search results where parents increasingly look for advice.",
    benefits: [
      "Organic traffic that grows without incremental media spend",
      "Visibility in AI search results (ChatGPT, Perplexity, Google AI Overviews)",
      "Reach parents searching for subscription boxes, gifts and child development content",
    ],
    timeSaved: "From Meta dependency to sustainable organic acquisition that compounds over time",
    deliverables: [
      "SEO audit: technical, on-page and content gaps",
      "Keyword research: parent searches, school and childcare queries, gift occasions",
      "Content cluster strategy and editorial calendar",
      "Landing page copy and structure for key audience segments",
      "Blog and guide content: first batch of articles",
      "Internal linking structure and breadcrumb implementation",
      "Structured data (JSON-LD) for product, FAQ and organisation",
      "AEO optimisation: content structured for AI answer engines",
      "Content production workflow (with optional AI-assisted pipeline)",
      "Measurement plan and monthly SEO performance reporting",
    ],
  },
  {
    id: "WF3",
    title: "CRO & Audience-Specific Landing Pages",
    bucket: "Quick Win",
    rice: { reach: 9, impact: 2, confidencePct: 85, effort: 5 },
    impactLabel: "High",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 20, daysMax: 35, weeks: "6–10 weeks", daysLabel: "20–35 days" },
    cost: { min: 10000, max: 25000 },
    investmentLabel: "€10K–€25K",
    hideTimeline: true,
    summary:
      "Improve conversion rate and better align ad traffic with specific audiences, propositions and campaigns through targeted landing pages and structured A/B testing.",
    why: "Conversion rate has grown from 1.8% to 2.1%, but structural experimentation remains limited. Zappiebox explicitly identifies persona-specific landing pages, campaign pages and dynamic content as direct opportunities. Better ad-to-landing-page alignment typically delivers a faster return than increasing media spend.",
    benefits: [
      "More revenue from the same media budget through higher conversion",
      "Better ad-to-page alignment for parents, gift-givers, schools and international visitors",
      "A structured A/B testing backlog that continues to improve performance over time",
    ],
    timeSaved: "From generic homepage traffic to tailored landing experiences per audience and campaign",
    deliverables: [
      "CRO audit: funnel analysis, Shopify data, heatmaps and session recordings",
      "Persona mapping: parents, gift-givers, schools, German visitors, seasonal audiences",
      "Landing page template design (UX/UI) optimised for conversion",
      "Audience-specific pages: copywriting and Shopify implementation",
      "Campaign-specific and seasonal landing pages",
      "A/B test plan with hypotheses, priorities and measurement criteria",
      "Tracking setup: event definitions, funnel events and conversion goals",
      "Test backlog for ongoing CRO programme",
      "Reporting dashboard for landing page and test performance",
    ],
  },
  {
    id: "WF4",
    title: "Marketing Data & Performance Dashboard",
    bucket: "Big Bet",
    rice: { reach: 7, impact: 2, confidencePct: 70, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weeks", daysLabel: "25–45 days" },
    cost: { min: 15000, max: 35000 },
    investmentLabel: "€15K–€35K",
    hideTimeline: true,
    summary:
      "Enable better decisions on channels, campaigns, creatives, subscriptions and customer value through a central performance dashboard — built alongside the existing tracking partner.",
    why: "There is currently insufficient reliable data to draw strong conclusions per channel and creative. Without a data foundation, investment decisions are based on gut feel. A central dashboard translates raw data into actionable insights on CAC, LTV, ROAS, cohorts and subscription retention.",
    benefits: [
      "Data-driven channel and creative investment decisions",
      "Insight into CAC, LTV, ROAS and payback period per channel",
      "Subscription retention and churn visibility to reduce involuntary cancellations",
    ],
    timeSaved: "From gut-feel investment decisions to evidence-based channel and creative optimisation",
    deliverables: [
      "Data source inventory and tracking architecture review",
      "Alignment with the existing tracking partner to prevent duplication",
      "KPI framework: definitions for CAC, LTV, ROAS, payback period, churn",
      "Channel reporting: spend, revenue and ROAS per channel",
      "Creative performance dashboard: hooks, formats and audience breakdown",
      "Cohort analysis: subscription revenue and retention by acquisition cohort",
      "Subscription analytics: prepaid vs recurring, churn triggers, lifecycle stages",
      "Dashboard design and BI implementation",
      "Data quality checks and monitoring",
      "Reporting rhythm and decision frameworks for media investment",
    ],
  },
  {
    id: "WF5",
    title: "YouTube Ads Pilot",
    bucket: "Quick Win",
    rice: { reach: 6, impact: 1, confidencePct: 75, effort: 3 },
    impactLabel: "Medium",
    phaseOriginal: "NOW",
    phaseRevised: "NOW",
    effort: { daysMin: 15, daysMax: 25, weeks: "4–8 weeks", daysLabel: "15–25 days" },
    cost: { min: 7500, max: 17500 },
    investmentLabel: "€7.5K–€17.5K",
    hideTimeline: true,
    summary:
      "Test YouTube as an additional paid channel in a contained pilot — repurposing existing content, without immediately building a full organic YouTube strategy.",
    why: "Zappiebox is hesitant about organic YouTube content due to production capacity, but sees paid ads as a potential opportunity. A contained pilot with repurposed UGC limits investment risk and delivers concrete evidence for whether YouTube Ads make sense before committing to larger budgets.",
    benefits: [
      "Low-risk channel test using existing or repurposed UGC content",
      "Reach parents in a discovery mindset on YouTube",
      "Data to inform future YouTube investment decisions",
    ],
    timeSaved: "From channel uncertainty to evidence-based YouTube investment decisions",
    deliverables: [
      "YouTube Ads strategy and audience targeting plan",
      "Campaign structure: awareness, consideration and retargeting layers",
      "Script development for 6s, 15s and 30s formats",
      "Video creative production or repurposing from existing UGC",
      "Creative testing plan across formats and messages",
      "Tracking and measurement setup for YouTube attribution",
      "Pilot campaign setup and launch",
      "Performance evaluation and go/no-go recommendation",
    ],
    investmentNote: "Recommended test media budget: €10K–€25K (separate from this investment)",
  },
  {
    id: "WF6",
    title: "B2B Partnership Proposition",
    bucket: "Big Bet",
    rice: { reach: 5, impact: 2, confidencePct: 65, effort: 6 },
    impactLabel: "High",
    phaseOriginal: "NEXT",
    phaseRevised: "NEXT",
    effort: { daysMin: 25, daysMax: 40, weeks: "8–12 weeks", daysLabel: "25–40 days" },
    cost: { min: 15000, max: 35000 },
    investmentLabel: "€15K–€35K",
    hideTimeline: true,
    summary:
      "Develop a repeatable commercial model for schools, childcare organisations and other business partners — validated through a structured pilot before scaling.",
    why: "Partnerships with schools and childcare are explicitly named as a growth opportunity. However, the exact proposition, pricing structure and commercial approach have not yet been validated. A structured proposition development and pilot prevents investing in sales infrastructure before there is proven demand.",
    benefits: [
      "A new acquisition channel independent of Meta and organic search",
      "Scalable model for recurring B2B relationships",
      "Validated commercial proposition before investing in B2B website or CRM",
    ],
    timeSaved: "From an untested B2B idea to a validated proposition with first paying partners",
    deliverables: [
      "Market and segment research: schools, childcare, corporate gifting",
      "Value proposition design per segment",
      "Partnership model options: bulk orders, subscriptions, gifting programmes",
      "Pricing and discount structure",
      "Sales materials: pitch deck, one-pager, email templates",
      "Pilot partner selection criteria and outreach approach",
      "Partner onboarding process",
      "KPIs for proposition validation",
      "Pilot execution and evaluation report with go/no-go recommendation",
    ],
  },
  {
    id: "WF7",
    title: "B2B Website or Subdomain",
    bucket: "Incremental",
    rice: { reach: 5, impact: 1, confidencePct: 60, effort: 6 },
    impactLabel: "Medium",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 25, daysMax: 45, weeks: "8–14 weeks", daysLabel: "25–45 days" },
    cost: { min: 12000, max: 30000 },
    investmentLabel: "€12K–€30K",
    hideTimeline: true,
    summary:
      "A separate digital environment for business audiences, partnerships and lead generation — built only after the B2B proposition is validated.",
    why: "Once the B2B proposition is validated (WF6), Zappiebox needs a targeted digital environment for business customers. Building a full B2B website before there is a proven sales model risks significant investment with uncertain return. We recommend this as a Phase 3 project.",
    benefits: [
      "A professional digital presence for business and institutional buyers",
      "Lead capture and nurturing for schools, childcare and corporate partners",
      "Separation of B2C and B2B messaging for better conversion",
    ],
    timeSaved: "From missing B2B digital presence to a targeted conversion environment for business customers",
    deliverables: [
      "Information architecture for B2B environment",
      "B2B proposition copy and messaging",
      "UX/UI design for landing pages, product pages and lead forms",
      "Case studies and partner information",
      "Lead form design and CRM integration",
      "Analytics and conversion tracking",
      "Implementation within Shopify or as separate subdomain",
    ],
  },
  {
    id: "WF8",
    title: "CRM for Partnerships & Physical Channels",
    bucket: "Incremental",
    rice: { reach: 4, impact: 2, confidencePct: 50, effort: 7 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 30, daysMax: 55, weeks: "10–18 weeks", daysLabel: "30–55 days" },
    cost: { min: 15000, max: 40000 },
    investmentLabel: "€15K–€40K",
    hideTimeline: true,
    summary:
      "Centrally manage leads, schools, childcare organisations, partners and physical sales channels — once B2B activity reaches sufficient volume to warrant structured CRM.",
    why: "Once the B2B channel gains traction, managing leads and partnerships in spreadsheets becomes unscalable. A CRM prevents opportunities from falling through the cracks. We recommend starting light and scaling only after the B2B proposition is validated and pipeline volume is confirmed.",
    benefits: [
      "No leads or partnerships lost due to lack of follow-up structure",
      "Clear pipeline visibility for B2B sales activity",
      "Foundation for automating partner communications and reporting",
    ],
    timeSaved: "From spreadsheet-based partner management to structured pipeline and follow-up",
    deliverables: [
      "CRM selection recommendation based on requirements",
      "Process design: lead stages, contact and organisation model",
      "Pipeline setup with status definitions and ownership",
      "Task and follow-up workflow configuration",
      "Email and form integrations",
      "Automations for common workflows",
      "Reporting dashboards for pipeline and partner activity",
      "Training and documentation",
    ],
  },
  {
    id: "WF9",
    title: "Germany Market Validation Pilot",
    bucket: "Big Bet",
    rice: { reach: 7, impact: 2, confidencePct: 45, effort: 8 },
    impactLabel: "High",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 35, daysMax: 65, weeks: "12–20 weeks", daysLabel: "35–65 days" },
    cost: { min: 20000, max: 50000 },
    investmentLabel: "€20K–€50K",
    hideTimeline: true,
    summary:
      "Validate a local German market approach that goes beyond translated Dutch ads — through research, localised creative and a contained pilot campaign.",
    why: "Simply translating Dutch ads proves insufficient for the German market, which has different positioning expectations, competitive dynamics and cultural nuances. At the same time, cashflow constraints and the maturity of the current marketing machine limit immediate full expansion. A structured validation pilot delivers a go/no-go decision before significant resources are committed.",
    benefits: [
      "A data-backed go/no-go decision for Germany before large-scale investment",
      "Local creative and positioning tested under real market conditions",
      "Foundation for full German market launch if the pilot validates",
    ],
    timeSaved: "From assumed market fit to validated German growth strategy",
    deliverables: [
      "German market and competitive research",
      "Local positioning and value proposition",
      "Cultural localisation beyond translation: copy, offer, imagery",
      "German ad creative (static, video, UGC)",
      "German landing pages with localised conversion copy",
      "Pricing and offer testing for German audience",
      "Channel strategy: Meta, Google, TikTok for Germany",
      "Pilot campaign setup and execution",
      "CRO and performance tracking for German traffic",
      "Pilot evaluation report with go/no-go recommendation",
    ],
    investmentNote: "A full German market launch would require €50K–€100K+ separately",
  },
  {
    id: "WF10",
    title: "Headless Shopify Rebuild",
    bucket: "Incremental",
    rice: { reach: 6, impact: 1, confidencePct: 30, effort: 10 },
    impactLabel: "Medium",
    phaseOriginal: "NEAR",
    phaseRevised: "NEAR",
    effort: { daysMin: 65, daysMax: 140, weeks: "24–52 weeks", daysLabel: "65–140 days" },
    cost: { min: 60000, max: 150000 },
    investmentLabel: "€60K–€150K",
    hideTimeline: true,
    summary:
      "A new headless commerce architecture based on Shopify — with greater flexibility and performance potential. Not recommended as a priority at this stage.",
    why: "The current Shopify theme managed by a freelancer shows no clear technical bottlenecks that require a headless rebuild. A headless migration carries very high effort, cost and migration risk without a demonstrated commercial or technical problem that cannot be solved within the existing Shopify setup. We advise against this project until concrete limitations are proven.",
    benefits: [
      "Full control over front-end performance and UX",
      "Decoupled architecture for future scalability",
      "Custom checkout and subscription flow possibilities",
    ],
    timeSaved: "Potential: from freelancer-managed theme to fully custom commerce architecture",
    deliverables: [
      "Technical discovery and architecture design",
      "UX/UI design for new front-end",
      "Front-end development (Next.js or equivalent)",
      "Shopify Storefront API integration",
      "CMS integration",
      "Analytics and tracking migration",
      "SEO migration plan and execution",
      "Checkout and Firmhouse integration",
      "QA, performance testing and launch",
      "Maintenance documentation",
    ],
  },
];
